package com.lenscatalog;

import java.util.Locale;

/**
 * UI strings: Spanish and English. Drawn in the bundled Roboto (assets/fonts),
 * which has Latin-1, Latin Extended-A, Cyrillic and the usual punctuation
 * (· – … « »); marks such as stars, ticks and arrows are drawn as shapes by
 * MenuView, never typed here (the camera's own font has none of them).
 */
final class Text {
    private Text() {}

    private static final String[][] T = {
        // { key, es, en }
        { "title", "LensCatalog", "LensCatalog" },
        { "checking", "Comprobando objetivo…", "Checking lens…" },
        { "e_lens", "Objetivo electrónico detectado:", "Electronic lens detected:" },
        { "e_lens_hint", "Nada que hacer. Pulsa MENU para salir.", "Nothing to do. Press MENU to exit." },
        { "no_e_lens", "Sin objetivo electrónico", "No electronic lens" },
        { "no_e_lens_hint", "Elige el objetivo manual conectado.", "Choose the attached manual lens." },
        { "brands", "Marcas", "Brands" },
        { "models", "Modelos", "Models" },
        { "favorites", "Favoritos", "Favourites" },
        { "no_favorites", "Sin favoritos", "No favourites" },
        { "no_favorites_hint", "Márcalos con la estrella en la ficha del objetivo.", "Star them on a lens's page." },
        { "last_used", "Último utilizado", "Last used" },
        { "manual", "Datos manuales", "Manual data" },
        { "manual_intro", "Para un objetivo que no está en el catálogo.", "For a lens that is not in the catalogue." },
        { "manual_preview", "EXIF: {0}", "EXIF: {0}" },
        { "diagnostics", "Diagnóstico", "Diagnostics" },
        { "manual_brand", "Marca: Manual", "Brand: Manual" },
        { "manual_model", "Modelo: Manual", "Model: Manual" },
        { "focal", "Focal", "Focal length" },
        { "focal_min", "Focal mín.", "Min. focal" },
        { "focal_max", "Focal máx.", "Max. focal" },
        { "max_aperture", "Apertura máx.", "Max. aperture" },
        { "skip", "(omitir)", "(skip)" },
        { "mm", "mm", "mm" },
        { "range", "Rango", "Range" },
        { "wide_end", "(angular)", "(wide end)" },
        { "zoom", "ZOOM", "ZOOM" },
        { "prime", "FIJO", "PRIME" },
        { "apply", "Aplicar", "Apply" },
        { "add_fav", "Añadir a favoritos", "Add to favourites" },
        { "in_fav", "En favoritos", "In favourites" },
        { "summary_ibis", "IBIS", "IBIS" },
        { "summary_exif", "EXIF", "EXIF" },
        { "applied", "{0} · IBIS {1} · EXIF OK", "{0} · IBIS {1} · EXIF OK" },
        { "applied_title", "Aplicado", "Applied" },
        { "sim", "SIM", "SIM" },
        { "sim_note", "Simulador: llamadas registradas, nada aplicado.", "Simulator: calls logged, nothing applied." },
        { "zoom_warn", "Si mueves el zoom, vuelve a aplicar.", "If you move the zoom, re-apply." },
        { "exit", "Saliendo…", "Exiting…" },
        { "res_lens", "Objetivo", "Lens" },
        { "res_lc", "Corrección", "Correction" },
        { "res_ok", "Listo", "Ready" },
        { "res_sim", "Simulado", "Simulated" },
        { "res_failed", "Error", "Failed" },
        { "res_unsupported", "No admitido: usa «Escribir EXIF»", "Not supported: use “Write EXIF”" },
        { "tag_exif", "Escribir EXIF en fotos", "Write EXIF to photos" },
        { "tagging", "Etiquetando fotos…", "Tagging photos…" },
        { "tagging_hint", "Buscando fotos nuevas en la tarjeta.", "Looking for new photos on the card." },
        { "tag_done", "Fotos etiquetadas", "Photos tagged" },
        { "tag_result", "{0} etiquetadas - {1} ya estaban - {2} fallos ({3} ms)", "{0} tagged - {1} already - {2} failed ({3} ms)" },
        { "tag_tagged", "Etiquetadas", "Tagged" },
        { "tag_already", "Ya estaban", "Already tagged" },
        { "tag_electronic", "Obj. electrónico", "Electronic lens" },
        { "tag_failed", "Fallos", "Failed" },
        { "tag_time", "Tiempo", "Time" },
        { "tag_nosession", "Sin objetivo", "No lens" },
        { "tag_nosession_hint", "Hechas antes de aplicar un objetivo en la app.", "Taken before a lens was applied." },
        { "ibis_from", "(objetivo {0} mm)", "(lens {0} mm)" },
        { "ibis_off", "Apagado en la cámara", "Off in the camera" },
        // SteadyShot in the camera's settings store (IbisSlots)
        { "ibis_cal", "Calibrar SteadyShot", "Calibrate SteadyShot" },
        { "ibis_cal_intro", "La focal que la app pone solo dura mientras la app está abierta: la cámara vuelve a lo que guarda en su memoria de ajustes. Para que quede, la app tiene que saber en qué lugar la guarda tu cámara. Se averigua una vez, en tres pasos, cambiando el menú de la cámara entre ellos.",
          "The focal length the app sets lasts only while the app is open: the camera goes back to what its settings memory holds. For it to stay, the app must learn where your camera keeps it. Found once, in three steps, changing the camera's menu between them." },
        { "ibis_step1", "Paso 1 de 3. Sal de la app. En el menú de la cámara pon SteadyShot Adjust: Auto. Vuelve a abrir la app, entra aquí y pulsa OK.",
          "Step 1 of 3. Leave the app. In the camera's menu set SteadyShot Adjust: Auto. Open the app again, come here and press OK." },
        { "ibis_step2", "Paso 2 de 3. Sal de la app. Pon SteadyShot Adjust: Manual y la focal en {0} mm. Vuelve a abrir la app, entra aquí y pulsa OK.",
          "Step 2 of 3. Leave the app. Set SteadyShot Adjust: Manual and the focal length to {0} mm. Open the app again, come here and press OK." },
        { "ibis_step3", "Paso 3 de 3. Sal de la app. Cambia la focal del SteadyShot a {0} mm. Vuelve a abrir la app, entra aquí y pulsa OK.",
          "Step 3 of 3. Leave the app. Change the SteadyShot focal length to {0} mm. Open the app again, come here and press OK." },
        { "ibis_done", "Calibrado. Al aplicar un objetivo, la focal queda en la cámara aunque la app se cierre.",
          "Calibrated. When a lens is applied, its focal length stays in the camera with the app closed." },
        { "ibis_record", "Registrar paso {0}", "Record step {0}" },
        { "ibis_again", "Empezar de nuevo", "Start again" },
        { "ibis_recording", "Leyendo la memoria de ajustes…", "Reading the settings memory…" },
        { "ibis_recorded", "Paso {0} registrado", "Step {0} recorded" },
        { "ibis_next_hint", "Sal de la app, cambia el menú de la cámara como dice el paso siguiente y vuelve.",
          "Leave the app, change the camera's menu as the next step says, and come back." },
        { "ibis_found_title", "SteadyShot calibrado", "SteadyShot calibrated" },
        { "ibis_notfound_title", "No se encontró el ajuste", "Setting not found" },
        { "ibis_notfound_hint", "Repite los tres pasos. Los archivos IBISCAL*.TXT de la tarjeta sirven para analizarlo.",
          "Try the three steps again. The IBISCAL*.TXT files on the card help analyse it." },
        { "ibis_focal_slot", "Focal", "Focal length" },
        { "ibis_mode_slot", "Modo", "Mode" },
        { "ibis_mode_none", "no encontrado (pon Manual en el menú)", "not found (set Manual in the menu)" },
        { "ibis_store", "SteadyShot en la cámara", "SteadyShot in the camera" },
        { "ibis_kept", "{0} mm · guardado", "{0} mm · kept" },
        { "ibis_live_only", "{0} mm · solo mientras la app está abierta", "{0} mm · only while the app is open" },
        { "ibis_uncalibrated", "sin calibrar", "not calibrated" },
        { "ibis_calibrated", "calibrado", "calibrated" },
        { "ibis_apply_hint", "Calibra SteadyShot en Diagnóstico para que la focal quede al salir.",
          "Calibrate SteadyShot in Diagnostics so the focal length stays when you leave." },
        { "lg_record", "Registrar", "Record" },
        { "store_dump", "Volcar ajustes de la cámara", "Dump camera settings" },
        { "store_dumping", "Volcando ajustes…", "Dumping settings…" },
        { "store_file", "Archivo", "File" },
        { "store_slots", "Valores", "Slots" },
        { "store_hint", "Cambia un ajuste en el menú y vuelca otra vez.", "Change one setting in the menu, then dump again." },
        { "store_camera_only", "Solo en la cámara (no en el simulador).", "On the camera only (not in the simulator)." },
        { "tag_failed_hint", "Detalle en «Ver registro».", "Details in “View log”." },
        { "view_log", "Ver registro", "View log" },
        { "log_title", "Registro", "Log" },
        { "log_empty", "(vacío)", "(empty)" },
        { "log_lines", "{0} líneas", "{0} lines" },
        { "auto_exit", "Salir auto tras aplicar", "Auto-exit after apply" },
        { "on", "SÍ", "ON" },
        { "off", "NO", "OFF" },
        { "fav_added", "Añadido a favoritos", "Added to favourites" },
        { "fav_removed", "Quitado de favoritos", "Removed from favourites" },
        { "lens_correction", "Corrección de lente", "Lens correction" },
        { "lc_adjust", "Ajustar corrección", "Adjust correction" },
        { "lc_reset", "Restablecer valores", "Reset values" },
        { "lc_on", "ON", "ON" },
        { "lc_off", "OFF", "OFF" },
        { "lc_applied", "LC OK", "LC OK" },
        { "lc_none", "sin ajustar", "not set" },
        { "lc_count", "{0} de 9", "{0} of 9" },
        { "lc_shading_w", "Viñeteo · brillo", "Shading · brightness" },
        { "lc_shading_wm", "Viñeteo · brillo medio", "Shading · mid brightness" },
        { "lc_shading_cr", "Viñeteo · rojo", "Shading · red" },
        { "lc_shading_cb", "Viñeteo · azul", "Shading · blue" },
        { "lc_shading_cm", "Viñeteo · color medio", "Shading · mid color" },
        { "lc_chroma_r", "Aberr. crom. · rojo", "Chr. aberr. · red" },
        { "lc_chroma_b", "Aberr. crom. · azul", "Chr. aberr. · blue" },
        { "lc_dist", "Distorsión", "Distortion" },
        { "lc_dist_m", "Distorsión · media", "Distortion · mid" },
        { "sec_quick", "Acceso rápido", "Quick access" },
        { "sec_catalog", "Catálogo", "Catalogue" },
        { "sec_tools", "Herramientas", "Tools" },
        { "n_lenses", "{0} objetivos", "{0} lenses" },
        { "n_lens", "{0} objetivo", "{0} lens" },
        { "n_brands", "{0} marcas", "{0} brands" },
        { "n_brand", "{0} marca", "{0} brand" },
        { "catalog_src", "Catálogo", "Catalogue" },
        { "catalog_apk", "{0} objetivos · interno", "{0} lenses · built-in" },
        { "catalog_card", "{0} objetivos · tarjeta", "{0} lenses · memory card" },
        { "app_version", "Versión", "Version" },
        { "camera_clock", "Reloj de la cámara", "Camera clock" },
        // adding a lens on the camera (UserLenses, Keyboard)
        { "add_lens", "Añadir objetivo", "Add a lens" },
        { "add_intro", "Un objetivo que no está en el catálogo. Se guarda en la app y en la tarjeta.",
          "A lens the catalogue lacks. Kept in the app and on the card." },
        { "edit_lens", "Editar objetivo", "Edit lens" },
        { "f_brand", "Marca", "Brand" },
        { "f_model", "Modelo", "Model" },
        { "f_mount", "Montura", "Mount" },
        { "f_type", "Tipo", "Type" },
        { "f_none", "—", "—" },
        { "f_empty", "(escribir)", "(type)" },
        { "save", "Guardar", "Save" },
        { "saved_title", "Objetivo guardado", "Lens saved" },
        { "saved_app", "En la app", "In the app" },
        { "saved_card", "En la tarjeta", "On the card" },
        { "saved_ok", "Guardado", "Saved" },
        { "saved_hint", "Ya está en el catálogo, con su marca.", "It is in the catalogue now, under its brand." },
        { "need_model", "Falta el modelo", "Model missing" },
        { "need_brand", "Falta la marca", "Brand missing" },
        { "delete_lens", "Borrar objetivo", "Delete lens" },
        { "delete_confirm", "¿Borrar? Pulsa OK otra vez", "Delete? Press OK again" },
        { "deleted_title", "Objetivo borrado", "Lens deleted" },
        { "mine", "PROPIO", "MINE" },
        { "my_lenses", "Objetivos propios", "My lenses" },
        { "my_lenses_card", "{0} · tarjeta OK", "{0} · card OK" },
        { "my_lenses_nocard", "{0} · tarjeta: {1}", "{0} · card: {1}" },
        { "kb_space", "Espacio", "Space" },
        { "kb_back", "Borrar", "Delete" },
        { "kb_clear", "Vaciar", "Clear" },
        { "kb_done", "Listo", "Done" },
        { "kb_chars", "{0}/{1}", "{0}/{1}" },
        { "lg_move", "Mover", "Move" },
        { "lg_type", "Escribir", "Type" },
        { "lg_done", "Listo", "Done" },
        { "lg_toggle", "Cambiar", "Toggle" },
        { "lg_brands", "Marcas", "Brands" },
        { "lg_mounts", "Monturas", "Mounts" },
        { "lg_save", "Guardar", "Save" },
        // the legend: what the keys do on this screen
        { "lg_choose", "Elegir", "Choose" },
        { "lg_page", "Página", "Page" },
        { "lg_open", "Entrar", "Open" },
        { "lg_ok", "OK", "OK" },
        { "lg_adjust", "Ajustar", "Adjust" },
        { "lg_back", "Atrás", "Back" },
        { "lg_exit", "Salir", "Exit" },
        { "lg_scroll", "Desplazar", "Scroll" },
        { "lg_home", "Inicio", "Home" },
    };

    private static boolean es() {
        return Locale.getDefault().getLanguage().equals("es");
    }

    static String get(String key) {
        for (String[] r : T) if (r[0].equals(key)) return es() ? r[1] : r[2];
        return key;
    }

    /** get(key) with {0}, {1}… replaced. */
    static String fmt(String key, String... args) {
        String s = get(key);
        for (int i = 0; i < args.length; i++) s = s.replace("{" + i + "}", args[i]);
        return s;
    }
}
